name: Deploy
on:
  push:
    branches:
      - main
    paths:
      - .github/**
      - src/**
      - index.html
      - vite.config.ts
      - yarn.lock

jobs:
  deploy:
    name: Deploy to Github Pages
    permissions:
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"

      - name: corepack
        run: |
          corepack enable
          yarn install

      - name: Validate
        run: |
          yarn typecheck
          yarn check-format
          yarn lint
          yarn test

      - name: Build
        run: |
          yarn tailwind
          yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: dist
