name: Deploy
on:
  push:
    branches:
      - main
    paths:
      - .github/**
      - src/**
      - index.html

jobs:
  check-format:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - run: |
          yarn
          yarn check-format

  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - run: |
          yarn
          yarn lint

  test:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - run: |
          yarn
          yarn test

  typecheck:
    name: Typescript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - run: |
          yarn
          yarn typecheck

  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    needs: 
      - check-format
      - lint
      - test
      - typecheck
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Build
        run: |
          yarn
          yarn tailwind
          yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
